# Generated by Django 5.1.3 on 2025-03-19 15:14

import django.contrib.gis.db.models.fields
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthFacility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="name")),
                ("amenity", models.CharField(blank=True, max_length=50, verbose_name="amenity")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326, verbose_name="location"
                    ),
                ),
                ("osm_id", models.BigIntegerField(blank=True, null=True, verbose_name="OSM id")),
                ("osm_type", models.CharField(blank=True, max_length=255, verbose_name="OSM type")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        help_text="The database level timestamp of when the record was created.",
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated_at")),
            ],
            options={
                "verbose_name": "Health Facility",
                "verbose_name_plural": "Health Facilities",
            },
        ),
    ]
