# Generated by Django 5.1.6 on 2025-04-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0008_area_population_density_hd_avg"),
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthfacility",
            name="administrative_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_care_facilities",
                related_query_name="health_care_facility",
                to="administrative.area",
                verbose_name="administrative area",
            ),
        ),
    ]
