# docker-compose-dev.yaml

# To avoid conflicts with already existing services on the host,
# exposed ports are incremented by 1 on their leftmost digit.
#
# From the project root directory:
#
# - To start, run:
# ```sh
# docker compose -f ./docker/development/docker-compose.yaml up
# ```
#
# - To stop, run:
# ```sh
# docker compose -f ./docker/development/docker-compose.yaml down
# ```
#
# - To stop and clean, run:
# ```sh
# docker compose -f ./docker/development/docker-compose.yaml down -v --remove-orphans
# ```

version: "3.8"

services:
  # Postgres Database with PostGIS for development
  #
  # Usage:
  #
  # - localhost uri:
  # ```
  # postgresql+psycopg://iipdash:iipdash@localhost:6432/iipdash
  # ```
  #
  # -docker uri:
  # ```
  # postgresql+psycopg://iipdash:iipdash@iipdash-dev-pg:5432/iipdash
  # ```
  iipdash-dev-pg:
    image: postgis/postgis:17-3.5
    container_name: iipdash-dev-pg
    environment:
      POSTGRES_USER: ${DEVELOPMENT_DATABASE_USER:-iipdash}
      POSTGRES_PASSWORD: ${DEVELOPMENT_DATABASE_PASSWORD:-iipdash}
      POSTGRES_DB: ${DEVELOPMENT_DATABASE_NAME:-iipdash}
    volumes:
      - ../postgis/docker-entrypoint-initdb.d/initdb-postgis.sh:/docker-entrypoint-initdb.d/10_postgis.sh
      - iipdash-dev-pg-data:/var/lib/postgresql/data
    ports:
      - ${DEVELOPMENT_DATABASE_PORT:-6432}:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DEVELOPMENT_DATABASE_USER:-iipdash}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Postgres Database with PostGIS for testing
  #
  # Usage:
  #
  # - localhost uri:
  # ```
  # postgresql+psycopg://test_iipdash:test_iipdash@localhost:7432/test_iipdash
  # ```
  #
  # - docker uri:
  # ```
  # postgresql+psycopg://test_iipdash:test_iipdash@iipdash-test-pg:5432/test_iipdash
  # ```
  iipdash-test-pg:
    image: postgis/postgis:17-3.5
    container_name: iipdash-test-pg
    environment:
      POSTGRES_USER: ${TEST_DATABASE_USER:-test_iipdash}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD:-test_iipdash}
      POSTGRES_DB: ${TEST_DATABASE_NAME:-test_iipdash}
    volumes:
      - ../postgis/docker-entrypoint-initdb.d/initdb-postgis.sh:/docker-entrypoint-initdb.d/10_postgis.sh
      - iipdash-test-pg-data:/var/lib/postgresql/data
    ports:
      - ${TEST_DATABASE_PORT:-7432}:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DATABASE_USER:-test_iipdash}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ for development
  #
  # Usage:
  #
  # - localhost uri:
  # ```
  # amqp://iipdash:iipdash@localhost:6672//
  # ```
  #
  # - docker uri:
  # ```
  # amqp://iipdash:iipdash@iipdash-dev-rabbitmq:5672//
  # ```
  iipdash-dev-rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: iipdash-dev-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${DEVELOPMENT_RABBITMQ_USER:-iipdash}
      RABBITMQ_DEFAULT_PASS: ${DEVELOPMENT_RABBITMQ_PASSWORD:-iipdash}
    ports:
      - ${DEVELOPMENT_RABBITMQ_PORT:-6672:5672}
      - 26672:15672
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:

  iipdash-dev-pg-data:
    driver: local

  iipdash-test-pg-data:
    driver: local
