"""
Django settings for iipdash project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import sys
from pathlib import Path

from django.utils.translation import gettext_lazy as _

import environ
from corsheaders.defaults import default_headers as cors_default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.append(str(BASE_DIR / "apps"))

env = environ.Env()
env.read_env(str(BASE_DIR / ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-7b%v^$@s8ct1c)yx^dr8-@h=oqr&%66q&9!)owdb)fc=adtb2",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", False)

# https://docs.djangoproject.com/en/5.1/ref/settings/#allowed-hosts
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

INTERNAL_IPS = env.list("INTERNAL_IPS", default=["127.0.0.1"])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "treebeard",
    "django_countries",
    "import_export",
    "rest_framework",
    "rest_framework_gis",
    "oauth2_provider",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "corsheaders",
    "users",
    "administrative",
    "education",
    "infrastructure",
    "debug_toolbar",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.common.CommonMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "iipdash.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "iipdash.context_processors.site",
            ],
        },
    },
]

WSGI_APPLICATION = "iipdash.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# https://docs.djangoproject.com/en/5.1/ref/settings/#test

DATABASES = {
    "default": {
        "ENGINE": env("DATABASE_ENGINE", default="django.contrib.gis.db.backends.postgis"),
        "NAME": env("DATABASE_NAME", default="iipdash"),
        "USER": env("DATABASE_USER", default="iipdash"),
        "PASSWORD": env("DATABASE_PASSWORD", default="iipdash"),
        "HOST": env("DATABASE_HOST", default="localhost"),
        "PORT": env.int("DATABASE_PORT", default=5432),
        "CONN_MAX_AGE": env.int("DATABASE_CONN_MAX_AGE", default=0),
        "ATOMIC_REQUESTS": env.bool("DATABASE_ATOMIC_REQUESTS", default=True),
        "CONN_HEALTH_CHECKS": env.bool("CONN_HEALTH_CHECKS", default=False),
        "TEST": {
            "NAME": env("TEST_DATABASE_NAME", default="test_iipdash"),
            "USER": env("TEST_DATABASE_USER", default="test_iipdash"),
            "PASSWORD": env("TEST_DATABASE_PASSWORD", default="test_iipdash"),
            "HOST": env("TEST_DATABASE_HOST", default="localhost"),
            "PORT": env.int("TEST_DATABASE_PORT", default=5432),
            "MIGRATE": env.bool("TEST_DATABASE_MIGRATE", default=True),
        },
    }
}

# Auth

AUTH_USER_MODEL = "users.User"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Password hashers
# https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-PASSWORD_HASHERS
# https://docs.djangoproject.com/en/5.1/topics/auth/passwords/
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = env("LANGUAGE_CODE", default="en-us")

TIME_ZONE = env("TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True

# Countries
# https://github.com/SmileyChris/django-countries?tab=readme-ov-file#customize-the-country-list
COUNTRIES_ONLY = [("CD", _("Democratic Republic of the Congo")), "MW", "ZM"]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# https://docs.djangoproject.com/en/5.1/howto/static-files/deployment/

STATICFILES_DIRS = env.list(
    "STATICFILES_DIRS",
    default=[
        BASE_DIR / "static",
        BASE_DIR / "assets/dist",
    ],
)

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

STATIC_URL = env("STATIC_URL", default="/static/")

STATIC_ROOT = env("STATIC_ROOT", default=(BASE_DIR / "static_root"))


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Site

SITE_NAME = env("SITE_NAME", default="IIP dashboard")

SITE_API_NAME = env("SITE_API_NAME", default=f"{SITE_NAME} API")

SITE_API_URL = env("SITE_API_URL", default="")

# Admin site

ADMIN_SITE_NAME = env("ADMIN_SITE_HEADER", default=SITE_NAME)

ADMIN_SITE_HEADER = env("ADMIN_SITE_HEADER", default=SITE_NAME)

ADMIN_INDEX_TITLE = env("ADMIN_INDEX_TITLE", default="Administration")

# REST framework settings

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticatedOrReadOnly"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": env("API_PAGE_SIZE", default=100),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "SEARCH_PARAM": "q",
    "ORDERING_PARAM": "ordering",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# REST framework GIS settings
BBOX_PARAM = env("BBOX_PARAM", default="in_bbox")
TILE_PARAM = env("TILE_PARAM", default="in_tile")
POINT_PARAM = env("POINT_PARAM", default="point")
DIST_PARAM = env("DIST_PARAM", default="radius")


SPECTACULAR_SETTINGS = {
    "TITLE": SITE_API_NAME,
    "DESCRIPTION": "",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_PUBLIC": False,
    "SERVERS": [
        {
            "url": "/api",
            "description": "Default API server",
        },
    ],
    "SCHEMA_PATH_PREFIX": "/api",
    "SCHEMA_PATH_PREFIX_TRIM": True,
    "REDOC_DIST": "SIDECAR",
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
}


# CORS

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])

CORS_ALLOWED_ORIGIN_REGEXES = env.list("CORS_ALLOWED_ORIGIN_REGEXES", default=[])

CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=DEBUG)

CORS_ALLOW_HEADERS = env.list("CORS_ALLOW_HEADERS", default=cors_default_headers)

# Administrative

ADMINISTRATIVE_AREAS_SIMPLIFICATION_TOLERANCE = env.float("ADMINISTRATIVE_AREAS_SIMPLIFICATION_TOLERANCE", default=1.0)
