#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --no-input --clear

chmod a+rX $STATIC_ROOT
chmod a+rX $MEDIA_ROOT

exec gunicorn iipdash.wsgi --bind 0.0.0.0:5000 --chdir=/iipdash
