# Generated by Django 5.1.8 on 2025-06-18 09:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import hazards.files
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative", "0008_area_population_density_hd_avg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hazard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="name")),
                ("code", models.SlugField(blank=True, null=True, unique=True, verbose_name="code")),
                (
                    "description",
                    models.TextField(blank=True, help_text="A long-form description.", verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
            ],
            options={
                "verbose_name": "Hazard",
                "verbose_name_plural": "Hazards",
            },
        ),
        migrations.CreateModel(
            name="ExposureCoverage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                (
                    "tiff",
                    models.FileField(
                        blank=True,
                        help_text="The file is expected to contain one band.",
                        max_length=510,
                        upload_to=hazards.files.hazard_exposure_tiff_path,
                        verbose_name="hazard exposure GeoTIFF",
                    ),
                ),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        editable=False,
                        help_text="hazard exposure raster data stored in the database.",
                        null=True,
                        srid=4326,
                        verbose_name="hazard exposure",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
                (
                    "administrative_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hazards_exposure_coverages",
                        related_query_name="hazards_exposure_coverage",
                        to="administrative.area",
                        verbose_name="administrative area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hazard Exposure Coverage",
                "verbose_name_plural": "Hazard Exposure Coverages",
            },
        ),
        migrations.CreateModel(
            name="HazardExposure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                (
                    "population_exposed",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="population exposed"),
                ),
                (
                    "population_exposed_percent",
                    models.FloatField(blank=True, null=True, verbose_name="population exposed (percentage)"),
                ),
                (
                    "population_exposed_ev",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="economically vulnerable population exposed"
                    ),
                ),
                (
                    "population_exposed_ev_percent",
                    models.FloatField(
                        blank=True, null=True, verbose_name="economically vulnerable population exposed (percentage)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
                (
                    "coverage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exposures",
                        related_query_name="exposure",
                        to="hazards.exposurecoverage",
                        verbose_name="coverage",
                    ),
                ),
                (
                    "hazards",
                    models.ManyToManyField(
                        blank=True,
                        related_name="exposures",
                        related_query_name="exposure",
                        to="hazards.hazard",
                        verbose_name="hazards",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hazards Exposure",
                "verbose_name_plural": "Hazards Exposures",
            },
        ),
    ]
