# Generated by Django 5.1.8 on 2025-06-23 14:32

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hazards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrbanizationDegree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="name")),
                ("code", models.SlugField(blank=True, null=True, unique=True, verbose_name="code")),
                (
                    "description",
                    models.TextField(blank=True, help_text="A long-form description.", verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
            ],
            options={
                "verbose_name": "Degree of Urbanization",
                "verbose_name_plural": "Degrees of Urbanization",
            },
        ),
        migrations.AddField(
            model_name="hazardexposure",
            name="urbanization_degree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exposures",
                related_query_name="exposure",
                to="hazards.urbanizationdegree",
                verbose_name="degree of urbanization",
            ),
        ),
    ]
