# Generated by Django 5.1.8 on 2025-07-18 10:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hazards", "0003_hazardexposure_hazards_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="hazardexposure",
            name="hazards_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                default=list,
                editable=False,
                null=True,
                size=None,
                verbose_name="hazards codes",
            ),
        ),
    ]
