# Generated by Django 5.1.8 on 2025-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hazards", "0004_add_hazardexposure_hazards_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="urbanizationdegree",
            name="group",
            field=models.CharField(
                blank=True, choices=[("urban", "Urban"), ("rural", "Rural")], max_length=64, verbose_name="group"
            ),
        ),
    ]
