"""
Administrative Area admin configuration

This module defines defines the admin interface for the
:class:`~apps.administrative.models.Area` model. It integrates features from
:class:`treebeard.admin.TreeAdmin`, :class:`django.contrib.gis.admin.GISModelAdmin`,
and :class:`import_export.admin.ImportExportModelAdmin` to provide a
hierarchical view, geographic data management, and data import/export
functionalities.

References:
    - :class:`~apps.administrative.models.Area`
    - :class:`treebeard.admin.TreeAdmin`
    - :class:`django.contrib.gis.admin.GISModelAdmin`
    - :class:`import_export.admin.ImportExportModelAdmin`
    - :class:`treebeard.forms.MoveNodeForm`
"""

from django.contrib.gis import admin
from django.contrib.gis.admin import GISModelAdmin

from import_export.admin import ImportExportModelAdmin
from treebeard.admin import TreeAdmin
from treebeard.forms import MoveNodeForm, movenodeform_factory

from .models import Area


@admin.register(Area)
class AreaAdmin(TreeAdmin, GISModelAdmin, ImportExportModelAdmin):
    """
    Admin interface configuration for the :class:`~apps.administrative.models.Area` model.

    This class extends :class:`treebeard.admin.TreeAdmin` for managing
    hierarchical structures, :class:`django.contrib.gis.admin.GISModelAdmin`
    for managing geographic data, and
    :class:`import_export.admin.ImportExportModelAdmin` for data import and
    export.
    """

    #: A list of fields to display in the admin change list view
    list_display: list[str] = ["name", "type_code", "country", "id", "uuid"]

    #: A list of fields in the admin's list view that link to the detailed
    #: area editing page.
    list_display_links: list[str] = ["name", "id", "uuid"]

    #: A list of fields that can be searched in the admin interface.
    search_fields: list[str] = ["name"]

    #: A list of fields that are displayed as read-only in the admin interface.
    readonly_fields: list[str] = ["id", "uuid", "full_name", "created_at", "updated_at"]

    #: The custom form for managing hierarchical areas. Generated by
    #: :func:`~treebeard.forms.movenodeform_factory`.
    form: MoveNodeForm = movenodeform_factory(Area)
