# Generated by Django 5.1.3 on 2024-12-02 09:08

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpticalFibre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, db_index=True, max_length=2, verbose_name="country"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, geography=True, null=True, srid=4326, verbose_name="geometry"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
            ],
            options={
                "verbose_name": "Optical Fibre Network",
                "verbose_name_plural": "Optical Fibre Networks",
            },
        ),
        migrations.CreateModel(
            name="CellTower",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                (
                    "network_type",
                    models.CharField(
                        blank=True,
                        help_text="Examples; GSM, UMTS, LTE or CDMA.",
                        max_length=255,
                        verbose_name="network type",
                    ),
                ),
                (
                    "mcc",
                    models.SmallIntegerField(
                        blank=True, help_text="Example 265 for Malawi", null=True, verbose_name="mobile country code"
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326, verbose_name="location"
                    ),
                ),
                (
                    "location_is_approximate",
                    models.BooleanField(blank=True, null=True, verbose_name="location is approximate"),
                ),
                (
                    "range",
                    models.FloatField(
                        blank=True,
                        help_text="Estimate of cell range",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="range (meters)",
                    ),
                ),
                ("src_created", models.DateTimeField(blank=True, null=True, verbose_name="source record created at")),
                (
                    "src_updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="source record updated at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
                (
                    "administrative_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infrastructure_cell_towers",
                        related_query_name="infrastructure_cell_tower",
                        to="administrative.area",
                        verbose_name="administrative area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell Tower",
                "verbose_name_plural": "Cell Towers",
            },
        ),
    ]
