# Generated by Django 5.1.3 on 2025-01-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OpticalFibre",
            new_name="FiberOptic",
        ),
        migrations.AlterModelOptions(
            name="fiberoptic",
            options={"verbose_name": "Fiber Optic Network", "verbose_name_plural": "Fiber Optic Networks"},
        ),
        migrations.AlterField(
            model_name="celltower",
            name="mcc",
            field=models.SmallIntegerField(
                blank=True, help_text="Example 650 for Malawi", null=True, verbose_name="mobile country code"
            ),
        ),
    ]
