# Generated by Django 5.1.4 on 2025-01-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0002_rename_opticalfibre_fiberoptic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="celltower",
            old_name="src_created",
            new_name="src_created_at",
        ),
    ]
