# Generated by Django 5.1.4 on 2025-01-08 06:28

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0001_initial"),
        ("infrastructure", "0003_rename_src_created_celltower_src_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celltower",
            name="administrative_area",
            field=models.ForeignKey(
                blank=True,
                help_text="The adminstrative area to which the cell tower belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="infrastructure_cell_towers",
                related_query_name="infrastructure_cell_tower",
                to="administrative.area",
                verbose_name="administrative area",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                help_text="The database level timestamp of when the cell tower was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional arbitrary data related to the cell tower.",
                verbose_name="extras",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="The spatial location of the cell tower.",
                null=True,
                srid=4326,
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="location_is_approximate",
            field=models.BooleanField(
                blank=True,
                help_text="Defines if coordinates of the cell tower are exact or approximate.",
                null=True,
                verbose_name="location is approximate",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="mcc",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The mobile country code of the cell tower. e.g., 650 for Malawi.",
                null=True,
                verbose_name="mobile country code",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="network_type",
            field=models.CharField(
                blank=True,
                help_text="The network type of the cell tower e.g., GSM, UMTS, LTE, CDMA.",
                max_length=255,
                verbose_name="network type",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="range",
            field=models.FloatField(
                blank=True,
                help_text="The estimated coverage range in meters of the cell tower.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="range (meters)",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="src_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The data source level timestamp of when the cell tower was created.",
                null=True,
                verbose_name="source record created at",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="src_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The data source level timestamp of when the cell tower was latest modified.",
                null=True,
                verbose_name="source record updated at",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The database level timestamp of when the cell tower was latest modified.",
                null=True,
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="celltower",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="A universally unique identifier (UUID) for the cell tower.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
