# Generated by Django 5.1.4 on 2025-01-11 08:59

import django.contrib.gis.db.models.fields
import django.db.models.functions.datetime
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_alter_celltower_administrative_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiberoptic",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                db_index=True,
                help_text="The country to which the fiber optic network belongs.",
                max_length=2,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="fiberoptic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                help_text="The database level timestamp of when the fiber optic network was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="fiberoptic",
            name="description",
            field=models.TextField(
                blank=True, help_text="A long-form description of the fiber optic network.", verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="fiberoptic",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional arbitrary data related to the fiber optic network.",
                verbose_name="extras",
            ),
        ),
        migrations.AlterField(
            model_name="fiberoptic",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiLineStringField(
                blank=True,
                geography=True,
                help_text="The spatial/geometric shape of the fiber optic network.",
                null=True,
                srid=4326,
                verbose_name="geometry",
            ),
        ),
        migrations.AlterField(
            model_name="fiberoptic",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A human-readable name of the fiber optic network.",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="fiberoptic",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The database level timestamp of when the fiber optic network was latest modified.",
                null=True,
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="fiberoptic",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="A universally unique identifier (UUID) for the fiber optic network",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
