# Generated by Django 5.1.3 on 2025-01-16 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0001_initial"),
        ("infrastructure", "0005_alter_fiberoptic_country_alter_fiberoptic_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiberoptic",
            name="administrative_area",
            field=models.ForeignKey(
                blank=True,
                help_text="The administrative area to which the fiber optic belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiber_optics",
                related_query_name="fiber_optic",
                to="administrative.area",
                verbose_name="administrative area",
            ),
        ),
    ]
