# Generated by Django 5.1.3 on 2025-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0006_fiberoptic_administrative_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiberoptic",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("operational", "Operational"),
                    ("under-construction", "Under construction"),
                    ("planned", "Planned"),
                    ("proposed", "Proposed"),
                ],
                db_index=True,
                max_length=128,
                verbose_name="status",
            ),
        ),
    ]
