# Generated by Django 5.1.3 on 2025-01-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0007_fiberoptic_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiberoptic",
            name="operator_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="operator name"),
        ),
    ]
