# Generated by Django 5.1.3 on 2025-01-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0008_fiberoptic_operator_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiberoptic",
            name="country",
        ),
    ]
