# Generated by Django 5.1.5 on 2025-02-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0003_alter_area_area_alter_area_code_alter_area_country_and_more"),
        ("infrastructure", "0009_remove_fiberoptic_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiberoptic",
            name="administrative_area",
            field=models.ForeignKey(
                blank=True,
                help_text="The administrative area to which the fiber optic network belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiber_optics",
                related_query_name="fiber_optic",
                to="administrative.area",
                verbose_name="administrative area",
            ),
        ),
        migrations.AlterField(
            model_name="fiberoptic",
            name="operator_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the network operator managing the fiber optic network.",
                max_length=255,
                verbose_name="operator name",
            ),
        ),
        migrations.AlterField(
            model_name="fiberoptic",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("operational", "Operational"),
                    ("under-construction", "Under construction"),
                    ("planned", "Planned"),
                    ("proposed", "Proposed"),
                ],
                db_index=True,
                help_text="The operational status of the fiber optic network.",
                max_length=128,
                verbose_name="status",
            ),
        ),
    ]
