# Generated by Django 5.1.3 on 2025-02-07 09:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import infrastructure.files
import uuid
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0003_alter_area_area_alter_area_code_alter_area_country_and_more"),
        ("infrastructure", "0010_alter_fiberoptic_administrative_area_and_more"),
    ]

    operations = [
        CreateExtension("postgis_raster"),
        migrations.CreateModel(
            name="NetworkGeneration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="name")),
                ("code", models.SlugField(blank=True, null=True, unique=True, verbose_name="code")),
                (
                    "description",
                    models.TextField(blank=True, help_text="A long-form description.", verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
            ],
            options={
                "verbose_name": "Mobile Network Generation",
                "verbose_name_plural": "Mobile Network Generations",
            },
        ),
        migrations.CreateModel(
            name="MobileCoverage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                (
                    "population_covered",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="population covered"),
                ),
                (
                    "population_covered_percent",
                    models.FloatField(blank=True, null=True, verbose_name="population covered percentage"),
                ),
                (
                    "tiff",
                    models.FileField(
                        blank=True,
                        max_length=510,
                        upload_to=infrastructure.files.mobile_coverage_tiff_path,
                        verbose_name="coverage GeoTIFF",
                    ),
                ),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        editable=False,
                        help_text="coverage raster data stored in the database.",
                        null=True,
                        srid=4326,
                        verbose_name="coverage raster",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
                (
                    "administrative_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infrastructure_mobile_coverages",
                        related_query_name="infrastructure_mobile_coverage",
                        to="administrative.area",
                        verbose_name="administrative area",
                    ),
                ),
                (
                    "network_generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_coverages",
                        related_query_name="mobile_coverage",
                        to="infrastructure.networkgeneration",
                        verbose_name="mobile network generation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Coverage",
                "verbose_name_plural": "Mobile Coverages",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("administrative_area", "network_generation"),
                        name="infrastructure_mobilecoverage_administrative_area_network_generation",
                    )
                ],
            },
        ),
    ]
