# Generated by Django 5.1.3 on 2025-02-07 10:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0003_alter_area_area_alter_area_code_alter_area_country_and_more"),
        ("infrastructure", "0011_networkgeneration_mobilecoverage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiberOpticNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                (
                    "node_type",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="node type"),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326, verbose_name="location"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
                (
                    "administrative_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiber_optic_nodes",
                        related_query_name="fiber_optic_node",
                        to="administrative.area",
                        verbose_name="administrative area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiber Optic Node",
                "verbose_name_plural": "Fiber Optic Nodes",
            },
        ),
    ]
