# Generated by Django 5.1.3 on 2025-02-10 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0003_alter_area_area_alter_area_code_alter_area_country_and_more"),
        ("infrastructure", "0012_fiberopticnode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celltower",
            name="administrative_area",
            field=models.ForeignKey(
                blank=True,
                help_text="The administrative area to which the cell tower belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cell_towers",
                related_query_name="cell_tower",
                to="administrative.area",
                verbose_name="administrative area",
            ),
        ),
        migrations.AlterField(
            model_name="mobilecoverage",
            name="administrative_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mobile_coverages",
                related_query_name="mobile_coverage",
                to="administrative.area",
                verbose_name="administrative area",
            ),
        ),
    ]
