# Generated by Django 5.1.3 on 2025-02-11 08:48

import infrastructure.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0013_update_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilecoverage",
            name="tiff",
            field=models.FileField(
                blank=True,
                help_text="The file is expected to contain one band.",
                max_length=510,
                upload_to=infrastructure.files.mobile_coverage_tiff_path,
                verbose_name="coverage GeoTIFF",
            ),
        ),
    ]
