# Generated by Django 5.1.3 on 2025-02-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0014_alter_mobilecoverage_tiff_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilecoverage",
            name="population_uncovered",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="population not covered"),
        ),
        migrations.AddField(
            model_name="mobilecoverage",
            name="population_uncovered_percent",
            field=models.FloatField(blank=True, null=True, verbose_name="population not covered (percentage)"),
        ),
        migrations.AlterField(
            model_name="mobilecoverage",
            name="population_covered_percent",
            field=models.FloatField(blank=True, null=True, verbose_name="population covered (percentage)"),
        ),
    ]
