# Generated by Django 5.1.3 on 2025-03-19 11:38

import django.contrib.gis.db.models.fields
import django.db.models.functions.datetime
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0015_add_mobilecoverage_population_uncovered"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricityNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A universally unique identifier (UUID)",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("voltage_kv", models.PositiveIntegerField(blank=True, null=True, verbose_name="voltage KV")),
                ("status", models.CharField(blank=True, max_length=255, verbose_name="status")),
                ("source", models.CharField(blank=True, max_length=255, verbose_name="source")),
                ("from_nm", models.CharField(blank=True, max_length=255, verbose_name="from nm")),
                ("to_nm", models.CharField(blank=True, max_length=255, verbose_name="to nm")),
                ("network_type", models.CharField(blank=True, max_length=255, verbose_name="network type")),
                ("country", django_countries.fields.CountryField(blank=True, max_length=2, verbose_name="country")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, geography=True, null=True, srid=4326, verbose_name="geometry"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        help_text="The database level timestamp of when the record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of when the record was last modified.",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Electricity Network",
                "verbose_name_plural": "Electricity Networks",
            },
        ),
    ]
