# Generated by Django 5.1.3 on 2025-03-30 09:47

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0008_area_population_density_hd_avg"),
        ("infrastructure", "0016_electricitynetwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternetSpeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                (
                    "mobile_speed",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="mobile speed (Mbps)"),
                ),
                ("fixed_speed", models.FloatField(blank=True, null=True, verbose_name="mobile speed (Mbps)")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
                (
                    "administrative_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internet_speeds",
                        related_query_name="internet_speed",
                        to="administrative.area",
                        verbose_name="administrative area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internet Speed",
                "verbose_name_plural": "Internet Speeds",
            },
        ),
    ]
