# Generated by Django 5.1.3 on 2025-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0017_internetspeed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internetspeed",
            name="fixed_speed",
            field=models.FloatField(blank=True, null=True, verbose_name="fixed speed (Mbps)"),
        ),
        migrations.AlterField(
            model_name="internetspeed",
            name="mobile_speed",
            field=models.FloatField(blank=True, null=True, verbose_name="mobile speed (Mbps)"),
        ),
    ]
