# Generated by Django 5.1.8 on 2025-06-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0008_area_population_density_hd_avg"),
        ("infrastructure", "0018_alter_internetspeed_fixed_and_mobile_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricitynetwork",
            name="administrative_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="electricity_networks",
                related_query_name="electricity_network",
                to="administrative.area",
                verbose_name="administrative area",
            ),
        ),
    ]
