# Generated by Django 5.1.8 on 2025-06-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0019_add_electricitynetwork_administrative_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electricitynetwork",
            name="country",
        ),
    ]
