# Generated by Django 5.1.8 on 2025-06-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0020_remove_electricitynetwork_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="celltower",
            name="operator_name",
            field=models.CharField(
                blank=True, help_text="Name of the network operator.", max_length=255, verbose_name="operator name"
            ),
        ),
    ]
