# Generated by Django 5.1.8 on 2025-06-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0021_celltower_operator_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="celltower",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="name"),
        ),
    ]
