# Generated by Django 5.1.5 on 2025-02-01 10:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="A universally unique identifier (UUID) for the user.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
