# Generated by Django 5.1.3 on 2025-03-19 07:37

import django.contrib.gis.db.models.fields
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demographics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelativeWealthIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A universally unique identifier (UUID).",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, help_text="The geo-spatial location.", srid=4326, verbose_name="location"
                    ),
                ),
                ("rwi", models.FloatField(verbose_name="rwi")),
                ("error", models.FloatField(blank=True, null=True, verbose_name="error")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        help_text="The database level timestamp of when the record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of when the record was last modified.",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relative Wealth Index",
                "verbose_name_plural": "Relative Wealth Indexes",
            },
        ),
    ]
