# Generated by Django 5.1.8 on 2025-06-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0008_area_population_density_hd_avg"),
        ("demographics", "0002_relativewealthindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="relativewealthindex",
            name="administrative_area",
            field=models.ForeignKey(
                blank=True,
                help_text="The administrative area to which the relative wealth index belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relative_wealth_indexes",
                related_query_name="relative_wealth_index",
                to="administrative.area",
                verbose_name="administrative area",
            ),
        ),
    ]
