# Generated by Django 5.1.8 on 2025-06-23 17:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demographics", "0003_add_relativewealthindex_administrative_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="relativewealthindex",
            name="bounds",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                geography=True,
                help_text="Boundaries of the area covered",
                null=True,
                srid=4326,
                verbose_name="bounds",
            ),
        ),
    ]
