# Generated by Django 5.1.3 on 2024-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="osm_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="OSM id"),
        ),
        migrations.AddField(
            model_name="institution",
            name="osm_type",
            field=models.CharField(blank=True, max_length=255, verbose_name="OSM type"),
        ),
    ]
