# Generated by Django 5.1.3 on 2025-01-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_institution_osm_id_institution_osm_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="has_electricity",
            field=models.BooleanField(blank=True, null=True, verbose_name="has electricity"),
        ),
    ]
