# Generated by Django 5.1.3 on 2025-01-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_institution_has_electricity"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="has_fiber_optic",
            field=models.BooleanField(blank=True, null=True, verbose_name="has fiber optic"),
        ),
    ]
