# Generated by Django 5.1.4 on 2025-01-05 16:48

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_institution_has_fiber_optic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.SlugField(
                blank=True, help_text="A unique slugified code for the category.", verbose_name="code"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                help_text="The database level timestamp of when the category was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="A long-form description of the category.", verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional arbitrary data related to the category.",
                verbose_name="extras",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, help_text="A human-readable name of the category.", max_length=255, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The database level timestamp of when the category was latest modified.",
                null=True,
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="A universally unique identifier (UUID) for the category.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
