# Generated by Django 5.1.3 on 2025-01-07 07:17

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0006_alter_ownership_code_alter_ownership_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="fon_distance",
            field=models.FloatField(
                blank=True,
                help_text="distance to the nearest fiber optic node (meters)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="distance to fiber node",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326, verbose_name="location"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="has_fiber_optic",
            field=models.BooleanField(blank=True, null=True, verbose_name="connected to fiber optic"),
        ),
    ]
