# Generated by Django 5.1.3 on 2025-01-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0007_institution_fon_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name="name"),
        ),
    ]
