# Generated by Django 5.1.3 on 2025-01-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0001_initial"),
        ("education", "0008_alter_institution_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="related_areas",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="related_education_institutions",
                related_query_name="related_education_institution",
                to="administrative.area",
                verbose_name="related administrative areas",
            ),
        ),
    ]
