# Generated by Django 5.1.5 on 2025-02-01 10:33

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0003_alter_area_area_alter_area_code_alter_area_country_and_more"),
        ("education", "0009_institution_related_areas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="address",
            field=models.CharField(
                blank=True, help_text="A physical address of the institution.", max_length=255, verbose_name="address"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="administrative_area",
            field=models.ForeignKey(
                blank=True,
                help_text="The administrative area to which the institution belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="education_institutions",
                related_query_name="education_institution",
                to="administrative.area",
                verbose_name="administrative area",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="The category to which the institution belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institutions",
                related_query_name="institution",
                to="education.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="code",
            field=models.CharField(
                blank=True, help_text="A unique code for the institution.", max_length=50, verbose_name="code"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                help_text="The database level timestamp of when the institution was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="description",
            field=models.TextField(
                blank=True, help_text="A long-form description of the institution.", verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="email",
            field=models.EmailField(
                blank=True, help_text="An email address of the institution.", max_length=254, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional arbitrary data related to the institution.",
                verbose_name="extras",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="fax",
            field=models.CharField(
                blank=True, help_text="A fax number of the institution.", max_length=50, verbose_name="fax"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="fon_distance",
            field=models.FloatField(
                blank=True,
                help_text="The distance to the nearest fiber optic node (meters).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="distance to fiber node",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="The spatial location of the institution.",
                null=True,
                srid=4326,
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="has_electricity",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the institution is connected to electricity or not.",
                null=True,
                verbose_name="has electricity",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="has_fiber_optic",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the institution is connected to fiber optic or not.",
                null=True,
                verbose_name="connected to fiber optic",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A human-readable name of the institution.",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="osm_id",
            field=models.BigIntegerField(
                blank=True, help_text="OpenStreetMap ID of the institution.", null=True, verbose_name="OSM id"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="osm_type",
            field=models.CharField(
                blank=True, help_text="OpenStreetMap type of the institution.", max_length=255, verbose_name="OSM type"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="ownership",
            field=models.ForeignKey(
                blank=True,
                help_text="The ownership to which the institution belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institutions",
                related_query_name="institution",
                to="education.ownership",
                verbose_name="ownership",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="phone",
            field=models.CharField(
                blank=True, help_text="A phone number of the institution.", max_length=50, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="A postal code for the institution's address.",
                max_length=50,
                verbose_name="postal code",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="related_areas",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="A set of administrative areas related to this institution.",
                related_name="related_education_institutions",
                related_query_name="related_education_institution",
                to="administrative.area",
                verbose_name="related administrative areas",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The database level timestamp of when the institution was latest modified.",
                null=True,
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="A universally unique identifier (UUID) for the institution.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="website",
            field=models.URLField(
                blank=True, help_text="A website URL of the institution.", null=True, verbose_name="website"
            ),
        ),
    ]
