# Generated by Django 5.1.3 on 2025-03-11 20:59

import django.contrib.postgres.fields
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("code", models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name="code")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="name")),
                ("code", models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name="code")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="tags",
                    ),
                ),
                ("source", models.TextField(blank=True, help_text="name of the data source", verbose_name="source")),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="link of the data source", verbose_name="source url"),
                ),
                ("attribution", models.CharField(blank=True, max_length=255, verbose_name="attribution")),
                ("license", models.TextField(blank=True, verbose_name="license")),
                ("is_public", models.BooleanField(blank=True, default=False, verbose_name="is public")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created at",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="updated at")),
                ("extras", models.JSONField(blank=True, default=dict, verbose_name="extras")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="layers",
                        related_query_name="layer",
                        to="catalog.category",
                        verbose_name="categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layer",
                "verbose_name_plural": "Layers",
            },
        ),
    ]
