# Generated by Django 5.1.3 on 2025-03-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.SlugField(
                blank=True,
                help_text="unique short code that can be used to identify the category",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="code",
            field=models.SlugField(
                blank=True,
                help_text="unique short code that can be used to identify the layer",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="code",
            ),
        ),
    ]
