# Generated by Django 5.1.3 on 2025-03-20 07:31

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_code_alter_layer_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="tiff",
            field=models.FileField(
                blank=True,
                help_text="The tiff file containing the data.",
                max_length=510,
                upload_to=catalog.models.layer_tiff_path,
                verbose_name="GeoTIFF",
            ),
        ),
    ]
