# Generated by Django 5.1.3 on 2025-03-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_layer_tiff"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="source_year",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="source year"),
        ),
    ]
