# Generated by Django 5.1.3 on 2024-12-01 09:02

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.functions.datetime
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('type_code', models.SlugField(blank=True, max_length=255, verbose_name='area type')),
                ('country', django_countries.fields.CountryField(blank=True, db_index=True, max_length=2, verbose_name='country')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('full_name', models.CharField(blank=True, help_text='automatically generated', max_length=255, verbose_name='full name')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='population')),
                ('population_male', models.PositiveIntegerField(blank=True, null=True, verbose_name='male population')),
                ('population_female', models.PositiveIntegerField(blank=True, null=True, verbose_name='female population')),
                ('population_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='population year')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='geometry')),
                ('area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='area (square meters)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('extras', models.JSONField(blank=True, default=dict, verbose_name='extras')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
    ]
