# Generated by Django 5.1.3 on 2025-01-31 07:31

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import MultiPolygon, Polygon
from django.db import migrations


def geometry2geom(area):
    """transform geometry to simplified EPSG:3857"""

    if area.geometry:
        geom = area.geometry.transform(3857, clone=True)
        geom = geom.simplify(1.0, preserve_topology=True)

        if isinstance(geom, Polygon):
            geom = MultiPolygon(geom)

        return geom


def populate_geoms(apps, schema_editor):
    """Populate geom data based on geometry."""

    Area = apps.get_model("administrative", "Area")
    for area in Area.objects.exclude(geometry=None).iterator():
        Area.objects.filter(pk=area.pk).update(geom=geometry2geom(area))


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, editable=False, null=True, srid=3857, verbose_name="geom"
            ),
        ),
        migrations.RunPython(populate_geoms),
    ]
