# Generated by Django 5.1.5 on 2025-02-01 10:33

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.functions.datetime
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0002_area_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="area",
            field=models.FloatField(
                blank=True,
                help_text="The total area of the `area` in square meters.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="area (square meters)",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="A unique short code or census code of the area.",
                max_length=50,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                db_index=True,
                help_text="The country to which the area belongs.",
                max_length=2,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="The database level timestamp of when the area was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="description",
            field=models.TextField(
                blank=True, help_text="A long-form description of the area.", verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional arbitrary data related to the area.",
                verbose_name="extras",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="The full name of the area, automatically generated.",
                max_length=255,
                verbose_name="full name",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                editable=False,
                help_text="A version of geometry optimized for performant rendering.",
                null=True,
                srid=3857,
                verbose_name="geom",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                geography=True,
                help_text="The spatial/geometric shape of the area.",
                null=True,
                srid=4326,
                verbose_name="geometry",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(
                help_text="A human-readable name of the area.", max_length=255, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="population",
            field=models.PositiveIntegerField(
                blank=True, help_text="The total population of the area.", null=True, verbose_name="population"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="population_female",
            field=models.PositiveIntegerField(
                blank=True, help_text="The female population of the area.", null=True, verbose_name="female population"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="population_male",
            field=models.PositiveIntegerField(
                blank=True, help_text="The male population of the area.", null=True, verbose_name="male population"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="population_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The year for the population data e.g., 2020.",
                null=True,
                verbose_name="population year",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="type_code",
            field=models.SlugField(
                blank=True,
                help_text="A hierarchy level name of the area, e.g., `province`, `district`, etc.",
                max_length=255,
                verbose_name="area type",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The database level timestamp of when the area was latest modified.",
                null=True,
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="A universally unique identifier (UUID) for the area.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
