# Generated by Django 5.1.3 on 2025-02-17 06:01

from django.db import migrations, models
from django.contrib.gis.db.models.functions import Area


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0003_alter_area_area_alter_area_code_alter_area_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="area",
        ),

        migrations.AddField(
            model_name="area",
            name="area",
            field=models.GeneratedField(
                db_persist=True,
                expression=Area("geometry"),
                help_text="The calculated total area of the `area` in square meters.",
                null=True,
                output_field=models.FloatField(null=True),
                verbose_name="area (square meters)",
            ),
        ),
    ]
