# Generated by Django 5.1.3 on 2025-03-10 08:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0004_change_area_area_to_generatedfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationDensityHD",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A universally unique identifier (UUID) for the area.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="The spatial location of the institution.",
                        srid=4326,
                        verbose_name="location",
                    ),
                ),
                (
                    "population_density",
                    models.FloatField(
                        db_index=True,
                        help_text="population in 1-arc-second-by-1-arc-second grid (30.87-meter-by-30.87 at the equator)",
                        verbose_name="population density",
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True, verbose_name="year")),
                (
                    "administrative_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="The administrative area to which the population density belongs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="population_densities_hd",
                        related_query_name="population_density_hd",
                        to="administrative.area",
                        verbose_name="administrative area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Population Density (HD)",
                "verbose_name_plural": "Population Densities (HD)",
                "indexes": [
                    models.Index(
                        fields=["administrative_area", "population_density"], name="admin_area_pop_density_idx"
                    )
                ],
            },
        ),
    ]
