# Generated by Django 5.1.3 on 2025-03-10 12:20

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0005_populationdensityhd"),
    ]

    operations = [
        migrations.AddField(
            model_name="populationdensityhd",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="The database level timestamp of when the record was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AddField(
            model_name="populationdensityhd",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of when the record was last modified.",
                null=True,
                verbose_name="updated at",
            ),
        ),
    ]
