# Generated by Django 5.1.3 on 2025-03-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0006_populationdensityhd_created_and_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PopulationDensityHD",
        ),
    ]
