# Generated by Django 5.1.3 on 2025-03-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0007_delete_populationdensityhd"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="population_density_hd_avg",
            field=models.FloatField(
                blank=True,
                help_text="Obtained by averaging of high resolution population density",
                null=True,
                verbose_name="population density (HD AVG)",
            ),
        ),
    ]
