# Generated by Django 5.1.8 on 2025-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0008_area_population_density_hd_avg"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="rwi_population_weighted",
            field=models.FloatField(
                blank=True,
                help_text="https://dataforgood.facebook.com/dfg/docs/tutorial-calculating-population-weighted-relative-wealth-index",
                null=True,
                verbose_name="population weighted relative wealth index",
            ),
        ),
    ]
